services:
  - type: web
    name: comments-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: POSTGRES_HOST
        fromDatabase:
          name: comments-db
          property: host
      - key: POSTGRES_DB
        fromDatabase:
          name: comments-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: comments-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: comments-db
          property: password
      - key: POSTGRES_DB_PORT
        fromDatabase:
          name: comments-db
          property: port
      - key: REDIS_URL
        fromService:
          name: comments-redis
          type: redis
          property: connectionString

  - type: redis
    name: comments-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: "allow all"

databases:
  - name: comments-db
    plan: free